server.port=${PORT:8080}
spring.web.resources.static-locations=classpath:/static/
spring.jackson.serialization.write_dates_as_timestamps=false
app.base-url=${BASE_URL:}
app.keepalive-interval=${KEEPALIVE_INTERVAL:600000}
spring.threads.virtual.enabled=true
